Feat implemented itemlist with preview at debt form
bablo-org/bablo_project_web pull request #100
Opened 2023-06-27 14:42 UTC by Iliustrator

2023-06-27 15:47 UTC, Pr0bka requested changes

2023-06-27 15:47 UTC, Pr0bka commented on src/components/DebtForm/GroupTransaction/ItemsList.tsx
> +  const [isSelectFiledFocused, setIsSelectFiledFocused] = useState<{
isSelectFieldFocused, setIsSelectFieldFocused

2023-06-27 15:47 UTC, Pr0bka commented on src/components/DebtForm/RenderPreview.tsx
> +  const isRenderUserCurrentUser = sender.includes(currentUserId);
isRenderedUserCurrentUser

2023-06-27 15:47 UTC, Pr0bka commented on src/components/DebtForm/RenderPreview.tsx
> +import DescriptionTooltip from '../Transactions/DescriptionTooltip';
If you want to use description tooltip in different places, not only in transactions, pls put into separate folder, like utils or UI

2023-06-27 15:47 UTC, Pr0bka commented on src/components/DebtForm/RenderPreview.tsx
> +import {
The entire code of transaction item is being duplicated in this file. I suppose you should move the transaction item  into components folder and reuse it in both places

2023-06-27 16:00 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.tsx
> +    isbillcalculation,
isBillCalculation

2023-06-27 16:02 UTC, AntonOvc commented on src/components/DebtForm/GroupTransaction/ItemsList.tsx
> +import {
pls rename file from `ItemsList.tsx` to `CheckItemsList.tsx`

2023-06-27 16:04 UTC, AntonOvc commented on src/components/DebtForm/GroupTransaction/ItemsList.tsx
> +    usedBillItemUsersDescription,
`isAddPerItemDescription` would be more understandable

2023-06-27 16:04 UTC, AntonOvc commented on src/components/DebtForm/GroupTransaction/ItemsList.tsx
> +  toogleUsedBillItemUsersDescription,
`toggleIsAddPerItemDescription` would be better

2023-06-27 16:05 UTC, AntonOvc commented on src/components/DebtForm/GroupTransaction/ItemsList.tsx
> +  generateBillItemUsersDescription,
generatePerItemDescription

2023-06-27 16:08 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +  isSumvalid: boolean;
isSumValid

2023-06-27 16:09 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +  isbillcalculation: boolean;
isBillCalculation

2023-06-27 16:10 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +  isbillcalculation: boolean;
or even you can name it `isBillModeOn`

2023-06-27 16:10 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +  billItemslist: BillItem[];
billItemsList

2023-06-27 16:11 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +  usedBillItemUsersDescription: boolean;
isAddPerItemDescription

2023-06-27 16:14 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +  billItemUsersDescription: UsersSum;
why billItemUsers**Description** is a type of Users**Sum**? Probably interface should be named ItemDescriptions?

2023-06-27 16:20 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +    removeBillItem(state, action: PayloadAction<number>) {
You introduced id field for `BillItem`, please consider look up and delete items from array by its `id`

2023-06-27 16:21 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +    toogleUsedBillItemUsersDescription(state) {
toggleIsAddPerItemDescription would be better

2023-06-27 16:23 UTC, AntonOvc commented on src/store/slices/addTransactionForm.ts
> +    shareSumOnToogleBillCulculation(state) {
recalculateSumOnModeSwitched?

2023-06-27 16:25 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.tsx
> +                {isbillcalculation && (
I like this approach 👍 
```
{statement && {}}
{!statement && {}}
```

2023-06-27 16:25 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.tsx
> +                              !validationProps.sum.testSum(enteredSum)) ||
to useMemo please

2023-06-27 16:29 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.tsx
>    Grid,
I think in the future we may require a functionality to add transaction from a modal or edit transaction. So I think it's good idea to split this big file into 3 separate blocks:
- AddSimpleTransactionForm.tsx
- AddBillTransactionForm.tsx
- outsource all related logic into `Page` folder

If now it is time consuming we can do this later

2023-06-27 16:30 UTC, AntonOvc commented on src/components/DebtForm/RenderPreview.tsx
> +import {
100% need to reuse existing component

2023-06-28 10:35 UTC, AntonOvc requested changes
#2 UI comment - not fixed, to be implemented in separate PR
#3 UI comment - not fixed

+ a few comments

2023-06-28 10:35 UTC, AntonOvc commented on src/components/DebtForm/RenderPreview.tsx
> +import { Grid, Typography, Divider } from '@mui/material';
word Render in file name is not desirable as each component in the whole app is a subject for rendering therefore please remove it here and in '`RenderTransactionItem.tsx`'

2023-06-28 10:35 UTC, AntonOvc commented on src/components/UI/RenderTransactionItem.tsx
> +import {
this is not just a UI utility but more complex component we are gonna use throughout the app to display transaction cards.
- Move it to components folder
- rename to TransactionItem.tsx

2023-06-28 10:35 UTC, AntonOvc commented on src/components/UI/RenderTransactionItem.tsx
> +  isApprovedStatus?: boolean;
instead of `isApprovedStatus`, `isApprovedStatus` etc you can pass just `TransactionStatus` enum value.
You can find it in models->enum->TransactionStatus.ts. This would be much better approach because imagine what could go wrong if you (or someone else) occasionally pass `isApprovedStatus={true`} and `isPendingStatus={true}`

2023-07-03 07:46 UTC, AntonOvc approved these changes

2023-07-03 10:18 UTC, Pr0bka approved these changes

2023-07-03 10:19 UTC, merged