Feat added new debt form
bablo-org/bablo_project_web pull request #11
Opened 2023-03-21 14:49 UTC by Pr0bka

2023-03-21 14:59 UTC, AntonOvc requested changes
Looks good! please check comments and merge

2023-03-21 14:59 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.js
> +  const clearForm = () => {
cannot clean up sender and receiver? 😄 please add functionality either here  or in subsequent PR

2023-03-21 14:59 UTC, AntonOvc commented on src/routes/AddTransactionPage.js
> +        <DebtForm></DebtForm>
```suggestion
        <DebtForm/>
```

2023-03-21 15:33 UTC, Pr0bka commented on src/components/DebtForm/DebtForm.js
> +  const [enteredSum, setenteredSum] = useState(``);
Fixed

2023-03-21 15:33 UTC, Pr0bka commented on src/components/DebtForm/DebtForm.js
> +  const [EnteredDate, setEnteredDate] = useState(``);
Fixed

2023-03-21 15:33 UTC, Pr0bka commented on src/routes/AddTransactionPage.js
> +        <DebtForm></DebtForm>
fixed

2023-03-21 15:33 UTC, Pr0bka commented on src/components/DebtForm/DebtForm.js
> +  const clearForm = () => {
later

2023-03-22 10:04 UTC, AntonOvc approved these changes

2023-03-22 10:06 UTC, merged