feat: upgrade avatarlist logic
bablo-org/bablo_project_web pull request #16
Opened 2023-03-26 10:13 UTC by Iliustrator

2023-03-26 10:33 UTC, AntonOvc requested changes

2023-03-26 10:33 UTC, AntonOvc commented on src/components/AvatarsList/AvatarsList.js
> +  const defaultUser = auth.currentUser.uid;
I think `currentUser` is better naming than `defaultUser`

2023-03-26 10:33 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.js
> +        <AvatarsList onUserSelected={setSender} currentUser={receiver}/>
I think not `currentUser` but `selectedUser`

2023-03-26 10:33 UTC, AntonOvc commented on src/components/DebtForm/DebtForm.js
> +        <AvatarsList onUserSelected={setSender} currentUser={receiver}/>
is better for naming

2023-03-26 14:05 UTC, AVPcm commented on src/components/AvatarsList/AvatarsList.js
> +      isBlock={currentUser === user.id || currentUser && currentUser !== defaultUser && user.id !== defaultUser}
isBlocked

2023-03-26 14:08 UTC, AVPcm commented on src/components/AvatarsList/AvatarsList.js
> +      isBlock={currentUser === user.id || currentUser && currentUser !== defaultUser && user.id !== defaultUser}
XXXuser -> XXXuserId (in fact we store only ID's here)

2023-03-27 08:53 UTC, AntonOvc approved these changes

2023-03-27 08:54 UTC, merged