feat: add change userdata logic
bablo-org/bablo_project_web pull request #20
Opened 2023-03-28 16:51 UTC by Iliustrator

2023-03-28 17:06 UTC, Pr0bka requested changes

2023-03-28 17:06 UTC, Pr0bka commented on src/components/UserProfile/UserProfile.js
> +            trasformString(reader.result);
maybe transformString?

2023-03-28 17:06 UTC, Pr0bka commented on src/components/UserProfile/UserProfile.js
> +    const trasformString = (string) => {
maybe transformString?

2023-03-28 17:06 UTC, Pr0bka commented on src/components/UserProfile/UserProfile.module.css
> +  .currencySelector {
Do not being used in js file

2023-03-28 17:14 UTC, AntonOvc requested changes
looks good just a few comments

2023-03-28 17:14 UTC, AntonOvc commented on src/components/UserProfile/UserProfile.js
> +    const encodedImage = {};
pls specify fields which would be added to the object at least as undefined

2023-03-28 17:14 UTC, AntonOvc commented on src/components/UserProfile/UserProfile.js
> +        } else if (userData.name) {
postUserAvatar(encodedImage.code, encodedImage.name)
                 .then((e) => {
                    return getDownloadURL(ref(storage, e.path))
                 })
                   .then((e) => {
                             console.log(e);
                             userData.avatar = e;
                             putUser(JSON.stringify(userData));
                         })

2023-03-28 17:14 UTC, AntonOvc commented on src/components/UserProfile/UserProfile.js
> +        } else if (userData.name) {
and add catch with console warn

2023-03-28 17:14 UTC, AntonOvc commented on src/components/UserProfile/UserProfile.js
> +        } else {
else return is redundant

2023-03-30 10:09 UTC, AntonOvc approved these changes

2023-03-30 10:22 UTC, Pr0bka approved these changes

2023-03-30 10:22 UTC, merged